### ISSUE TITLE
[Portal] Migrate to Angular signals

### ISSUE THREAD

**Issue by manekinekko** [Azure-Samples/contoso-real-estate#150]
- [ ] upgrade to Angular v16
- [ ] migrate to signals

Related package: https://github.com/Azure-Samples/contoso-real-estate/tree/main/packages/portal

**Comment by sumitparakh** [comment]
Can i take this up @manekinekko?

**Comment by manekinekko** [comment]
Sure @sumitparakh. Thank you 🙏

**Comment by sumitparakh** [comment]
Thank you @manekinekko 🤩
