### ISSUE TITLE
[Chore] Migrate all Node.js functions to the new v4 programming model  

### ISSUE THREAD

**Issue by manekinekko** [Azure-Samples/contoso-real-estate#174]
Read more: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-functions-version-4-of-the-node-js-programming-model-is-in/ba-p/3773541

**Comment by glaucia86** [comment]
cc: @anfibiacreativa and @manekinekko 

About the #214 it's just a boilerplate that @diberry and I did in the last time.

But consider for feature this new PR that I created today: #231 

Thanks!

**Comment by anfibiacreativa** [comment]
Closed with #231
