### ISSUE TITLE
Consider making this repo a GitHub template

### ISSUE THREAD

**Issue by savannahostrowski** [Azure-Samples/contoso-real-estate#204]
This repo uses git hooks to enforce commit message style.  However, you may want to consider that folks forking the repo may not want to abide by the same git conventions. I think if you were to make this repo a GitHub template in settings, this issue would be resolved.

As an aside, this also blocks `azd pipeline config` from working as we don't allow for custom commit messages during that command's execution today (filed https://github.com/Azure/azure-dev/issues/2260 to track this).

**Comment by anfibiacreativa** [comment]
Closed. Out of scope.
