### ISSUE TITLE
[Docs] Local and pipeline testing

### ISSUE THREAD

**Issue by core-dev-out** [Azure-Samples/contoso-real-estate#216]
I think the playwright docs could use a little framing so someone understands what needs to run and how to develope and run tests locally and to run in the pipeline. 

For example, in order to run the playwright e2e tests, the web app and apis need to be running. That might seem like a precondition/conf for playwright in the test package itself, or something that is done outside the playwright testing package at the root level with npm workspaces. 

An architectural drawing of how this works and then a package/file level view of which files are involved would be helpful.

**Comment by nitya** [comment]
> I think the playwright docs could use a little framing so someone understands what needs to run and how to develope and run tests locally and to run in the pipeline.
> 
> For example, in order to run the playwright e2e tests, the web app and apis need to be running. That might seem like a precondition/conf for playwright in the test package itself, or something that is done outside the playwright testing package at the root level with npm workspaces.
> 
> An architectural drawing of how this works and then a package/file level view of which files are involved would be helpful.

This is absolutely fantastic feedback - thank you for the issue @core-dev-out!
I am currently in the process of writing/migrating a "docs" package over that will act as a developer guide for the entire repo - and it has a Playwright section in it. I'll update this thread with the link when that gets merged (likely to take a week or so)

**Comment by nitya** [comment]
Sorry for the delay - just updating this thread to say that I've started refactoring the  `packages/testing` to reflect new capabilities (and recommendations) from Playwright team so expect changes soon. **I should have a first version in later this week and will update this discussion thread with details then**

On the documentation front - just added a `packages/docs` section that is adding a more detailed developer guide that can be run in local preview mode. **I will be adding a Testing section to that guide next week that will address the great feedback on diagrams and project structure** if that helps. _You can see [a GitHub Pages hosted version](https://30daysof.github.io/contoso-real-estate/) of the guide in my personal fork.
