### ISSUE TITLE
Updating/work-with this template for GHA and Azd Devcontainer feature.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/contoso-real-estate#239]
We are updating this template to support new features in `Github Action`.

1. For the Github Action feature: We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
<img width="302" alt="image" src="https://github.com/Azure-Samples/openai-plugin-fastapi/assets/81678720/b78e7045-08c4-4e09-90cd-ba0b22f50fe7">

2. For the Azd Devcontainer feature: We will add  the following code in `devcontainer.json` file.

``` 
"ghcr.io/azure/azure-dev/azd:latest": {}
``` 
And remove the relevant code for installing `azd` in `post-create-command.sh` file under `.devcontainer` folder.
```
curl -fsSL https://aka.ms/install-azd.sh | bash
```

@rajeshkamal5050 , @manekinekko , @sinedied for notification.

**Comment by SammyBloom** [comment]
Hi, please can I take on this task?

**Comment by crazy4pi314** [comment]
@SammyBloom are you still working on this issue? If not I can help :)

**Comment by SammyBloom** [comment]
> @SammyBloom are you still working on this issue? If not I can help :)
I have not been able to fix this. Please help me out. And if you don't mind, I would love to know how you fixed it when you do.

**Comment by anfibiacreativa** [comment]
Closed by #384

**Comment by zedy-wj** [comment]
@anfibiacreativa - It seems that your PR only updated the `Azd Devcontainer` feature, and the related feature of `GHA` did not seem to be updated.

**Comment by manekinekko** [comment]
Hi @zedy-wj I just opened a new PR to add the remaining changes: https://github.com/Azure-Samples/contoso-real-estate/pull/387

**Comment by zedy-wj** [comment]
Hi @manekinekko, Okay, LGTM!
