### ISSUE TITLE
Consider adding labels to the ports on devcontainer config to allow easy identification of deployed services

### ISSUE THREAD

**Issue by juliamuiruri4** [Azure-Samples/contoso-real-estate#240]
**Is your feature request related to a problem? Please describe.**
Opening the project in a Codespace starts 4 different ports with no quick way to identify which is which

**Describe the solution you'd like**
Consider adding labels to the ports on devcontainer config to allow easy identification of deployed services.

**Describe alternatives you've considered**

**Additional context**

**Comment by juliamuiruri4** [comment]
#243

**Comment by juliamuiruri4** [comment]
https://github.com/Azure-Samples/contoso-real-estate/pull/243 - fix

**Comment by manekinekko** [comment]
Fixed by #243
