### ISSUE TITLE
fix broken CSS in Portal

### ISSUE THREAD

**Issue by manekinekko** [Azure-Samples/contoso-real-estate#242]
Some UI parts are broken after migrating to Angular v16, probably due to underlying changes in Material Design in Angular v16.

Here are a few examples:

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/9adb03b0-3ad7-46b2-afdc-073b83881889)

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/257bf0e2-ca6a-4de9-9801-b7de52883617)

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/9e610881-3786-46c2-8386-b789ff8637f7)

**Comment by wenwei-lin** [comment]
I also found one in small screen size.

The footer links overlap logo:

![Screenshot 2023-08-07 175012](https://github.com/Azure-Samples/contoso-real-estate/assets/75592450/1d76d9a3-aa93-410b-b696-5d7b0a1a5c2c)

**Comment by Surya-V-28** [comment]
I also found some issues in responsive for the mobile screen

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/102609082/7daf7d2d-2b0d-42c0-bc78-6eaa5b00fb4a)
this is my first time , give the issues please let me know if there is any mistake

**Comment by stevensnicole** [comment]
I can take a look at that floating date format issue, I think that's what is shown fourth image above along with the 2nd image.

Do you want this split out and linked back to here?

**Comment by Surya-V-28** [comment]
It comes  under the CSS part right , so its make it here itself, so it is better for finding CSS issues and  Navbar can be done by css, I think its okay to stay here,. i am not sure tho ,I am open to any suggestions, correct me if i'm wrong

**Comment by alidotdeveloper** [comment]
can i work on that issues?

**Comment by Surya-V-28** [comment]
@juliamuiruri4 Can I work on this with  @YaminNather ?
