### ISSUE TITLE
Hack Together:  Create Sign In Form

### ISSUE THREAD

**Issue by samipak458** [Azure-Samples/contoso-real-estate#248]
## Problem Description:
As a user, I currently do not have a way to sign in to our application, which is causing frustration and hindering the user experience. Users are unable to access their personalized content and features, and this is limiting the overall functionality of the application.

## Solution Description:
We need to create a Sign In form that allows users to authenticate themselves and gain access to their accounts. The Sign In form should prompt users to enter their credentials (e.g., username/email and password) securely and efficiently. Once users submit their information, the system should verify the credentials and grant appropriate access privileges, redirecting them to the appropriate landing page upon successful sign-in.

## Alternatives Considered:

Authentication providers like OAuth or social media logins (e.g., Google, Facebook) to enable users to sign in without creating new credentials for our application is available but the CSS (styling) of the third-party authentication button need to be improved. 

## Additional Context
Creating the form will enable users to interact with personalized content, securely manage their accounts, and enjoy the full range of features our application has to offer. It is crucial to prioritize the implementation of the form to lay the foundation for a seamless and secure user experience.

**Comment by anfibiacreativa** [comment]
Thanks for the detailed reporting. Although your user story makes sense (and thank you for delivering such detailed description) anonymous user registration is out of scope at this time.
