### ISSUE TITLE
Hack Together: Create Sign Up Form

### ISSUE THREAD

**Issue by samipak458** [Azure-Samples/contoso-real-estate#249]
## Problem Description:

Currently, the web app doesn't have a Sign Up form, which makes it difficult for new users to register and access the services. This leads to potential users leaving the platform, resulting in lost opportunities for engagement and growth. We need to implement a Sign Up form to address this issue effectively.

## Solution Description:

Create a user-friendly Sign Up form that allows new users to easily register on our platform. The form should include standard fields like name, email address, password, and possibly additional relevant details. It should be intuitive, responsive, and ensure data security.

## Alternatives Considered:

As an alternative, we could use third-party authentication providers (OAuth) to allow users to sign up using their existing accounts from popular platforms like Google, Facebook, or Apple. However, this might not be suitable for users who prefer not to use these accounts for sign up or those who don't have them.

## Additional Context:

As a reference, I'm attaching a screenshot of a Sign Up form from a competitor's website that we find user-friendly and visually appealing. We believe implementing a similar solution will help improve user acquisition and retention.
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/52650290/c7fab873-6632-439b-9458-46d533ff0b98)

**Comment by anfibiacreativa** [comment]
Thanks for the detailed reporting. Although your user story makes sense (and thank you for delivering such detailed description) anonymous user registration is out of scope at this time.
