### ISSUE TITLE
Image Modal With Zoom In/Out - jQuery image-popup.js

### ISSUE THREAD

**Issue by thestarsahil** [Azure-Samples/contoso-real-estate#250]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Image Modal With Zoom In/Out - jQuery image-popup.js
Bascially When User Go through Featured Listings , Click into Preview Image , The Image  should be Zoom In/Out feature

**To Reproduce**

1. Go to Featured Listings
2. Select any component listed 
3. Trying to click on Image 
4. Haven't any response 

**Expected behavior**
Implementing the Image Modal With Zoom In/Out - jQuery image-popup.js feature

**Screenshots**
BEFORE : 

![Contoso-Real-Estate](https://github.com/Azure-Samples/contoso-real-estate/assets/84167034/35efca2c-df67-4e72-b1c0-535342cbd0fd)

AFTER :

![Untitled design (1)](https://github.com/Azure-Samples/contoso-real-estate/assets/84167034/55c5d418-f1aa-4a7f-98ba-40296d662221)
![Untitled design](https://github.com/Azure-Samples/contoso-real-estate/assets/84167034/342ee514-f910-4486-a378-a146b3850be7)

Please Assign Me in Under Hack Together , Good First Issue So I can work on it 
Thank You 
Sahil (MLSA )

**Comment by anfibiacreativa** [comment]
HI @thestarsahil that is a very nice UI feature however we may want to steer away from additional 3rd party dependencies that can't be tree-shaken or are not modular and that need to be loaded before other JS and therefore may impact performance. Maybe we can take a look at an Angular specific library that is small in size and would help us achieve the same results?

**Comment by anfibiacreativa** [comment]
We also suggest this is tackled together with https://github.com/Azure-Samples/contoso-real-estate/issues/253

**Comment by thestarsahil** [comment]
@anfibiacreativa Thank You For Reviewing 😃

**Comment by anfibiacreativa** [comment]
> @anfibiacreativa Thank You For Reviewing 😃

You're welcome! Should we assume you will teamup with @john0isaac to fix it together with #253 , or do you prefer trying with an Angular library?

**Comment by thestarsahil** [comment]
> > @anfibiacreativa Thank You For Reviewing 😃
> 
> You're welcome! Should we assume you will teamup with @john0isaac to fix it together with #253 , or do you prefer trying with an Angular library?

Yes I would love to work together @john0isaac to fix this bug out 🤘🧑‍💻
