### ISSUE TITLE
HackTogether: Fix Mismatch Prices

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/contoso-real-estate#251]
**Are you accessing the project from the GitHub Codespaces?**

- [x] Yes, I am using GitHub Codespaces.

**Describe the bug**
Prices on listing Home page are calculated based on the fourth list item while the prices in the detailed view page are calculated based on the fifth list item which results in price mismatch.

**To Reproduce**
1. Open the Portal
2. Click on any listing

**Expected behavior**
The price you see on the home page is the same as the listing page pricing.

**Screenshots**
The Date Returned
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/97f6ac16-b750-4aaa-af69-ec40ab63c186)

Portal Home Page Prices
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/b0553182-27a1-44c2-ba63-b8a677ceb53d)

Code that needs to be addressed `packages/portal/src/app/shared/card/card.component.ts`
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/a250445d-ece8-40da-8aa9-fc3150f50dc2)

Lisiting Page Price
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/a6d6378c-80ff-4c02-966c-bf5c4d67ebb8)

Code that needs to be addressed `packages/portal/src/app/shared/booking-form/booking-form.component.ts`
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/04090c9c-5edd-46d1-8432-88f7041c450a)

**Comment by john0isaac** [comment]
@anfibiacreativa you are most welcome!

**Comment by GmausDev** [comment]
Hi @juliamuiruri4  I was interested in #167 Not on this one :P

**Comment by john0isaac** [comment]
@juliamuiruri4 yes, definitely!

**Comment by juliamuiruri4** [comment]
#277

**Comment by juliamuiruri4** [comment]
> Hi @juliamuiruri4 I was interested in #167 Not on this one :P

Sorry for that - I've added you to 167. Thanks

**Comment by SammyBloom** [comment]
Hi @juliamuiruri4, I was interested in #257 and #251. I and @Surya-V-28

**Comment by john0isaac** [comment]
@juliamuiruri4 please, assign me to this issue as I will be making a pull request today.
