### ISSUE TITLE
HackTogether: Blurred Booking Options Accessible

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/contoso-real-estate#252]
**Are you accessing the project from the GitHub Codespaces?**

- [x] Yes, I am using GitHub Codespaces.

**Describe the bug**
User can edit booking form without the need to Login.

**To Reproduce**
1. Open the Portal
2. Click on any listing
3. Choose Options from the booking form

**Expected behavior**
The form isn't clickable if the user didn't login.

**Screenshots**
Listing Page Picking a Date
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/6eabede1-909f-4cd3-8c71-9d9763ef9556)

Listing Page Specifying number of guests
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/3ff5d0f4-d949-4efa-a233-6ac73c4177e3)

**Comment by Tanmai2002** [comment]
Can I work on this? @juliamuiruri4

**Comment by error9098x** [comment]
I already fixed this issue, I am making a PR

**Comment by error9098x** [comment]
I have opened the PR #287 , Please check that out :)
