### ISSUE TITLE
HackTogether: Fix Broken Search

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/contoso-real-estate#254]
**Are you accessing the project from the GitHub Codespaces?**

- [x] Yes, I am using GitHub Codespaces.

**Describe the bug**
When you try to search for a property by its name, location, anything, nothing happens.

**To Reproduce**
1. Open the Portal
2. Click on any Browse listings
3. Enter any keyword
4. Click on Search

**Expected behavior**
Show Clickable Properties in a list after you click on search.
[Bonus] Suggest text while the user types a keyword.

**Screenshots**
Search Page with Developer Tools
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/86d27e36-068a-4351-ba2e-220253134992)

**Comment by juliamuiruri4** [comment]
Thanks for reporting! We look forward to your PR, improving the search!

**Comment by john0isaac** [comment]
you are most welcome!

**Comment by anfibiacreativa** [comment]
Hi @john0isaac Do you have a PR in the making? Let us know!

**Comment by john0isaac** [comment]
Hi @anfibiacreativa,
Unfortunately no, I'm working on 3 different issues now.
