### ISSUE TITLE
HackTogether: Share Property to More social media

### ISSUE THREAD

**Issue by john0isaac** [Azure-Samples/contoso-real-estate#255]
**Are you accessing the project from the GitHub Codespaces?**

- [x] Yes, I am using GitHub Codespaces.

**Describe the bug**
When you try to share a property, it directs you to X social media platform.

**To Reproduce**
1. Open the Portal
2. Click on any listing
3. Click the share Icon

**Expected behavior**
Show a pop up or bar with multiple platforms to select from. (e.g. Facebook, LinkedIn, WhatsApp, Messenger, Instagram, and Telegram)
User selects the desired social media to share the property to.

**Screenshots**
Listing Page Share Property
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/97ebe8af-b528-4000-b072-9b2bb80d0579)

X Platform Sign in Page
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/7f0f80fa-b57a-4800-9432-77a47ac8e361)

**Comment by anfibiacreativa** [comment]
Thanks for reporting! We look forward to your PR!

**Comment by john0isaac** [comment]
@anfibiacreativa thank you!!

**Comment by juliamuiruri4** [comment]
Hey @john0isaac - There is a participant interested in working on this issue. @GmausDev 

Are you already working on this, or is there a possibility to team up with him?

**Comment by john0isaac** [comment]
@juliamuiruri4 Definitely yes, we can team up!

**Comment by john0isaac** [comment]
@GmausDev Let's start by dividing the work into two steps:
Step 1: Create a pop-up menu to choose the desired social media platform from when anyone clicks on the share icon.
Step 2: Add other social media platforms to the pop-up menu.

Unfortunately, we can't both work on the menu at the same time as step 1 is a blocker for step 2 so, please choose a step to start working on and I will continue after you.

Note: 
If you choose step 1 I will be waiting for you to finish it.
If you choose step 2 you will have to wait for me to finish step 1.

**Comment by GmausDev** [comment]
Okay ! 
@john0isaac  
Yep I was thinking the same , create a simple pop up and then add a stylish link tree.

My main expertise its back end and not in jss or tss , Take the step 1 and I´ll take the 2 I thinks its be more easier. 

What do you think?

**Comment by john0isaac** [comment]
@GmausDev Okay I will start working on it.
When I finish I will let you know here.

**Comment by bilalbyte** [comment]
Hey can I join you guys, I am a beginner and want to contribute, @GmausDev @john0isaac

**Comment by GmausDev** [comment]
Also , we can use teams or whatever. Btw , I´ll be on it ^^.

@bilalbyte  Maybe it´s not big enough but this hackathon its about contribute and colaborate! I had no problem but we need to figure out how to.

So @john0isaac  what do you think?

**Comment by bilalbyte** [comment]
I will be so grateful @GmausDev , Teams is a good option

**Comment by GmausDev** [comment]
Also im with another bug, if @john0isaac  and @juliamuiruri4  I can step out and you can take the second phase from john repo.

I had no problem and if you feel comfortable with this issue my part is yours.

If @juliamuiruri4  its agree with this assign @bilalbyte  to this issue , pls.

Thanks!

**Comment by john0isaac** [comment]
@GmausDev that's fine I can work with @bilalbyte.
@bilalbyte glad to work with you! 🤝🏼

@bilalbyte you can work on the same thing @GmausDev was going to work on as it will be an easy part and I can guide you through it.

@juliamuiruri4 please, assign @bilalbyte to this issue in addition to me and remove @GmausDev.

**Comment by GmausDev** [comment]
@john0isaac Removed :P. @bilalbyte  Have fun!

**Comment by Blackie360** [comment]
can you guys organize a google meet to help me start I don't how to start

**Comment by bilalbyte** [comment]
@GmausDev how can we connect?

**Comment by bilalbyte** [comment]
Thank you @john0isaac

**Comment by john0isaac** [comment]
@Blackie360 there are many online live sessions on Microsoft Reactor to guide you through your journey!
check the posting here! => #236 
Also, if you are looking for something to help you get started I would recommend checking this => https://github.com/Azure-Samples/contoso-real-estate/discussions/236#discussioncomment-6720718
Specifically, this video that guides you on how to get started => https://youtu.be/cAAE2LwwZEQ

**Comment by john0isaac** [comment]
Hey @bilalbyte,
I created a pull request that will close this issue.
I have set up everything for you to learn from and just copy and paste to add more platforms.

Once my pull request is merged I will include instructions for you to complete working from where I stopped!

**Comment by Kagirim** [comment]
Hello guys, who is working on what at the moment, are there specific places that still need some hands?

**Comment by bilalbyte** [comment]
> Hey @bilalbyte,
> I created a pull request that will close this issue.
> I have set up everything for you to learn from and just copy and paste to add more platforms.
> 
> Once my pull request is merged I will include instructions for you to complete working from where I stopped!

Sure, I'll be waiting for that

**Comment by john0isaac** [comment]
> Hello guys, who is working on what at the moment, are there specific places that still need some hands?

Great question!
You can check out this comment to know the answer.
https://github.com/Azure-Samples/contoso-real-estate/discussions/236#discussion-5434154
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/64026625/d598d216-1ede-4a57-bf44-ed62ed133a07)

to know which issues are available to work on check the issues tab.
https://github.com/Azure-Samples/contoso-real-estate/issues

**Comment by Kagirim** [comment]
> > Hello guys, who is working on what at the moment, are there specific places that still need some hands?
> 
> @Kagirim Great question! You can check out this comment to know the answer. [#236 (comment)](https://github.com/Azure-Samples/contoso-real-estate/discussions/236#discussion-5434154) ![image](https://user-images.githubusercontent.com/64026625/262108834-d598d216-1ede-4a57-bf44-ed62ed133a07.png)
> 
> to know which issues are available to work on check the issues tab. https://github.com/Azure-Samples/contoso-real-estate/issues

Thank you @john0isaac i was referring to the development progress on this issue on the share button. I'd like to know which section has not been handled yet.

**Comment by john0isaac** [comment]
Follow this pull request -> https://github.com/Azure-Samples/contoso-real-estate/pull/300
