### ISSUE TITLE
HackTogether: Authentication page

### ISSUE THREAD

**Issue by mzbhewtee** [Azure-Samples/contoso-real-estate#256]
**Are you accessing the project from the GitHub Codespaces?**

- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
In the tag, the text is not centered as it is meant to be judging from the scss code.

**To Reproduce**

1. Type in command npm run && npm start, then click on portal app 4280 in the ports
2. Click on Welcome, Guest on the top right side of the home page
3. See error

**Expected behavior**
* The text is supposed to be in the center of the button.
* The color choice should be more aesthetic

**Screenshots**
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/86835129/0ebec668-4d1b-4e1f-8f61-ecd5d8948ba7)

**OS (please complete the following information):**

- OS: Windows
- OS Version: 11
- npm version: 9.8.1
- Node.js version: 18.5.0
- output of `azd version`: azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

**Additional context**
None

**Comment by anfibiacreativa** [comment]
Hi @mzbhewtee ! We look forward to your contribution! Please note there are other issues around the styling of these buttons. It would be great for contributors to team up and collaborate! Have fun!
