### ISSUE TITLE
HackTogether: fix the hover effect of the user button

### ISSUE THREAD

**Issue by mzbhewtee** [Azure-Samples/contoso-real-estate#257]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
The hover effect of the user profile button on the top right corner doesn't look good

**To Reproduce**

1. Hover on the user profile button

**Expected behavior**
A full hover effect that covers the entire text and button

**Screenshots**
![effect](https://github.com/Azure-Samples/contoso-real-estate/assets/86835129/71022363-6200-49c5-92ac-bdf1127a6804)

**OS (please complete the following information):**
OS: Windows
OS Version: 11
npm version: 9.8.1
Node.js version: 18.5.0
output of azd version: azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

**Additional context**
None

**Comment by juliamuiruri4** [comment]
Hi @kelvink96 - there is a team already working on this one. @SammyBloom

Is there any other issue you'd want to pick up on?

**Comment by juliamuiruri4** [comment]
@SammyBloom - Hi, any update on this issue?
