### ISSUE TITLE
Hack together: Cannot move focus to other tabs (Payment History and Reservations) with keyboard in Profile page

### ISSUE THREAD

**Issue by wenwei-lin** [Azure-Samples/contoso-real-estate#259]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
 
When on the Profile page of the website, using the keyboard to navigate through tabs, I am unable to move focus to the "Payment History" and "Reservations" tabs.

**To Reproduce**

1. Login 
2. Go to Profile page 
3. Move focus with Tab key

**Expected behavior**

I expect that when I use the "Tab" key on the Profile page, the focus should cycle through all interactive elements on the page, including those within the "Profile" tab as well as the "Payment History" and "Reservations" tabs. This would enable users to efficiently navigate the page using keyboard controls.

**Screenshots**

![FocusIssue](https://github.com/Azure-Samples/contoso-real-estate/assets/75592450/1b2333cc-f09b-47ae-8344-b63dc9934884)

**OS (please complete the following information):**

- OS: Windows
- OS Version: 
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by manekinekko** [comment]
Hi @wenwei-lin can you navigating using these keyboards shortcuts: ![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/506089b7-70d2-43e9-94bb-e2ce5bd85b4a)

**Comment by wenwei-lin** [comment]
> Hi @wenwei-lin can you navigating using these keyboards shortcuts: ![image](https://user-images.githubusercontent.com/1699357/259982050-506089b7-70d2-43e9-94bb-e2ce5bd85b4a.png)

Yes, I can move focus with those keys.
