### ISSUE TITLE
Hacktogether: Fix responsive design for listing detail page

### ISSUE THREAD

**Issue by wenwei-lin** [Azure-Samples/contoso-real-estate#260]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
When in small screen size, the wide of listing detail page exceeds the max screen size.

**To Reproduce**

1. Open Developer Tool and change screen size to a mobile, like iPhone 12 Pro.
2. Click "View Listing" button of any items, like Practical loft downtown.
3. Check the width of page.

**Expected behavior**

The width of page should be the same as the max screen width.

**Screenshots**

![Screenshot 2023-08-07 181625](https://github.com/Azure-Samples/contoso-real-estate/assets/75592450/f5aa6fdf-0f06-4a2b-b630-ae7ad62f2bbc)

![Screenshot 2023-08-07 181636](https://github.com/Azure-Samples/contoso-real-estate/assets/75592450/638c346b-6d66-49f0-8943-025dbd62f63c)

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by anfibiacreativa** [comment]
Thanks for reporting! Looking forward to your PR!

**Comment by juliamuiruri4** [comment]
Currently being worked on by @DannyK05

**Comment by DannyK05** [comment]
I've made a pull request

**Comment by anfibiacreativa** [comment]
Closed with #275
