### ISSUE TITLE
HackTogether: fix search section

### ISSUE THREAD

**Issue by mzbhewtee** [Azure-Samples/contoso-real-estate#262]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
* The indicator for search should not be visible when active since it shows at the top
* the search button would look better if it were beside the input section
* The text under the search input is not aligning with it

**To Reproduce**

1. Click on Browse listing on the home page

**Expected behavior**
* I expect the indicator not to be visible when the input is active
* It will look much better and have better user interface if the search button is beside the search input instead of under
* I expect the text under the search input to be aligned with the search input section

**Screenshots**
![Screenshot 2023-08-07 133527](https://github.com/Azure-Samples/contoso-real-estate/assets/86835129/4ccb89f1-b71a-490c-b6a8-02ebaeb6f27f)
![Screenshot (705)](https://github.com/Azure-Samples/contoso-real-estate/assets/86835129/b363874f-ddea-4da6-90c6-74e8d794a6c9)

**Comment by anfibiacreativa** [comment]
Thanks for reporting! As with other CSS bugs, we recommend you take a look at the [Material Design](https://material.angular.io/) library to fix this bug. Thank you!
