### ISSUE TITLE
HackTogether: Fix feature listing for registered users

### ISSUE THREAD

**Issue by mzbhewtee** [Azure-Samples/contoso-real-estate#264]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
* The bookmark icon is too close to the image.
* The Property description is overlapping the bookmark icon.
* The short description for the listed property could be removed in order to create a minimalistic design. This description could be assessed when the user wants to know more about the property.

**To Reproduce**
Steps to reproduce the behavior

1. Go to home page after login

**Expected behavior**
* I expect the bookmark icon to be properly aligned/placed
* The property name/description should not overlap the bookmark icon
* A more aesthetic property listing

**Screenshots**
![Screenshot (707)](https://github.com/Azure-Samples/contoso-real-estate/assets/86835129/b43e1d7e-e8cf-4b30-b53d-f260961da520)

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**
Having the long description removed from the featured listing will let each card have equal height.

**Comment by anfibiacreativa** [comment]
Hi @mzbhewtee Thanks for reporting! We suggest you investigate this issue as related to [Angular material design](https://material.angular.io/). Thank you for participating. We look forward to your PR!

**Comment by mzbhewtee** [comment]
Hi @anfibiacreativa Thank you, i will investigate the issue.

**Comment by juliamuiruri4** [comment]
Suggestion to tackle with issue #242

**Comment by Tanmai2002** [comment]
Removing long description is not ideal recommendation. we can properly customize scss for having responsive cards with appropriate dimensions.

**Comment by Tanmai2002** [comment]
I am also willing to contribute and investigate together @mzbhewtee

**Comment by anfibiacreativa** [comment]
Do we have any updates? Thank you!
