### ISSUE TITLE
[Chore] PG errors

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#271]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [ X] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Updated to latest main, deploy succeeds but PG restore fails. 

**To Reproduce**

1. delete files in .azure so its a clean provision
2. azd auth login
3. azd provision
4. Terminal shows errors. So many that I don't have a complete log.

```
pg_restore: warning: errors ignored on restore: 309
PostgreSQL Database restored successfully
Setting STRAPI_DATABASE_MIGRATED to true in azd
```

**Expected behavior**
No errors? That seems reasonable. 

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 
[20230809-terminal-errors.txt](https://github.com/Azure-Samples/contoso-real-estate/files/12304527/20230809-terminal-errors.txt)

**Additional context**
The static web app works in the sense that the layout/nav/footer is there but the cms isn't working. I'm going to fork and try on a different account.

**Comment by manekinekko** [comment]
These warnings can be safely ignored.
