### ISSUE TITLE
Hack-together: Modify Account Menu

### ISSUE THREAD

**Issue by bilalbyte** [Azure-Samples/contoso-real-estate#274]
**Are you accessing the project from the GitHub Codespaces?**

- [x] Yes, I am using GitHub Codespaces.

**Describe the bug**
Upon clicking the account menu, it only presents the "Sign In" option and lacks other expected options.

**To Reproduce**
1. Observe the account menu, which displays "Welcome, Guest" by default.
2. Click on the account menu.
3. Note that the only option available is "Sign In" 

**Expected Behavior**
The account menu should contain the following options:
- Upon clicking the account menu options like "Sign In," and "Sign Up," should be listed.
- Upon clicking the account menu, it should accurately reflect the user's context:
For new users, options should include "Sign Up" in addition to the other choices.
If the user is already signed in, the menu should offer options like "Profile," "Settings," and "Sign Out."

**Screenshot**
<img width="958" alt="image" src="https://github.com/Azure-Samples/contoso-real-estate/assets/107356708/7e41ef3e-1c29-410b-9f45-b5836285219b">

**Comment by anfibiacreativa** [comment]
Hi @bilalbyte Thanks for participating. 'Sign up' capabilities are out of scope in the project at the moment.
