### ISSUE TITLE
[Hack-together] Incorrect Monthly Pricing

### ISSUE THREAD

**Issue by Tanmai2002** [Azure-Samples/contoso-real-estate#277]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [X ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
The Value for "Real Rent" has been incorrectly swapped with discount

**To Reproduce**
View the card

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/40868910/327284b7-521b-4e16-afd4-3a4cef470d96)

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by error9098x** [comment]
can I take this issue ?

**Comment by anfibiacreativa** [comment]
Fixed with #299
