### ISSUE TITLE
[Hack-together] Sign-in buttons change background color after reloading the page

### ISSUE THREAD

**Issue by richardrigutins** [Azure-Samples/contoso-real-estate#279]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
When navigating to the login page of the portal using the *login* button, all the sign-in buttons appear with their specific background color.
However, after reloading the page, the sign-in buttons all have a white background.
The same thing happens if I navigate directly to the `/auth/login`.

**To Reproduce**

1. Run the application with `npm run start`
2. Open the portal app
3. Click on *Welcome, Guest* on the top right side of the home page, and then *Login*
4. Press F5 or reload the page
5. The sign-in buttons have a white background

**Expected behavior**
The buttons shouldn't change color when reloading the page.

**Screenshots**

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/47950599/4571145d-2c54-4acb-bc12-dbfc9c381118)

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/47950599/acf24157-3f28-45ff-982f-3806297b4aee)

**OS (please complete the following information):**

- OS: Linux
- OS Version: codespaces-a87b53 5.15.0-1042-azure
- npm version: 9.8.1
- Node.js version: v18.15.0
- output of `azd version`: azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Additional context**
None.

**Comment by error9098x** [comment]
can I take this Issue ?

**Comment by juliamuiruri4** [comment]
@richardrigutins I see you have a couple of other issues. Okay if @error9098x works on this?

**Comment by richardrigutins** [comment]
Hi @error9098x, yes you can work on this issue, thank you 😊

**Comment by error9098x** [comment]
**Progress Update** I've resolved the issue and am in the process of submitting a pull request.

**Comment by error9098x** [comment]
*Progress Update* I've opened the PR #286  please have a look :) @anfibiacreativa
