### ISSUE TITLE
[Hack-together] Reservations are not displayed correctly

### ISSUE THREAD

**Issue by richardrigutins** [Azure-Samples/contoso-real-estate#282]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**

On the Reservations page of the portal, the list of reservations is not displayed correctly and some content is cut off.

**To Reproduce**

1. Run the application with `npm run start`
2. Open the portal app
3. Click on *Welcome, Guest* on the top right side of the home page, and then *Login*
4. Sign in
5. Go to the home page, select a listing, and create one or more reservations
6. Navigate to the Reservations page (`/me/reservations`)
7. The list of reservations is not displayed correctly

**Expected behavior**

The reservations should be shown correctly and all content should be visible.

**Screenshots**

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/47950599/a08d7b0f-bba8-4404-b9f8-c26a466099b7)

**OS (please complete the following information):**

- OS: Linux
- OS Version: codespaces-a87b53 5.15.0-1042-azure
- npm version: 9.8.1
- Node.js version: v18.15.0
- output of `azd version`: azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Additional context**
None.

**Comment by Tanmai2002** [comment]
This issue is already addressed in #242.

**Comment by juliamuiruri4** [comment]
Thanks for pointing that out @Tanmai2002 - Closing this issue now
