### ISSUE TITLE
[Hack-together] Sign-in buttons options  can have some style like logos ..etc

### ISSUE THREAD

**Issue by Surya-V-28** [Azure-Samples/contoso-real-estate#292]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [ Yes] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Instead just the name of the Sign options we can add some style as in logo of the sign option providers 

**To Reproduce**
 you can use the CSS file for adding the logos and some padding would be better 

1. Go to  Login Page
2. See the options

**Expected behavior**
 this would looks nice if its done 
 
 
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/102609082/32998bbf-f134-432d-8cfc-1db69d7f1c17)

**Additional context**
Add any other context to improve the page look.

**Comment by Surya-V-28** [comment]
@juliamuiruri4 I would like work on this with @YaminNather as team? can you assign this to me ?

**Comment by anfibiacreativa** [comment]
Thanks for reporting this issue! Looking forward to your contributions.
