### ISSUE TITLE
[Hack-together] feat: Including video tours of properties

### ISSUE THREAD

**Issue by VictorCodebase** [Azure-Samples/contoso-real-estate#295]
**Are you accessing the project from the GitHub Codespaces?**

- [✅] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Feature description**

**✅ Video Tours of Listed Houses**
By incorporating short video tours of the properties, users will enjoy a more immersive experience and a quicker understanding of the property's layout and features💫
This addition aims to improve user's interaction with the platform by reducing the number of clicks required to gain a comprehensive understanding of a property.🏘️

**✅Feature Details:**
To illustrate the feature's implementation, I've outlined a sample scenario:

When a user navigates to a property listing, an embedded video will be available, showcasing a brief tour of the property's interior and exterior.
This dynamic feature is expected to enhance user engagement and provide a more realistic representation of the property's attributes.

**✅Sample video tour**

https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/47105d84-4309-49ab-9cb5-92496ee7f0c9

**✅to view the full demo on adobeXD: **
https://xd.adobe.com/view/a61593cf-d597-4bc6-99f3-0bebc063e9e0-f346/?fullscreen

**✅Additional Input:**
I'm open to feedback on CSS design and any suggestions regarding the technical implementation. Your insights would be greatly appreciated🙂🙂!

**✅Screenshots**
For visual reference, I've included screenshots of the proposed feature in action:

![Screenshot 2023-08-20 211016](https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/5e324115-3f12-4763-8adc-ffb3d9dec3ef)

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/da8a9cd3-f065-45d3-8fd5-f80df6770d23)

**OS (please complete the following information):**

- OS: Windows 11 Home Single Language
- OS Version: 22H2
- npm version: (code spaces)
- Node.js version: (code spaces)
- output of `azd version`: 

**Additional context**

**Comment by anfibiacreativa** [comment]
Hi @VictorCodebase This is a great feature suggestion! We have strict compliance requirements around media. We could work on embedding a video player, providing it's not 3rd party or reviewing the licensing which may take a while. This is why this feature is out of scope for now. Please keep the suggestions coming!
