### ISSUE TITLE
[Hack-together] feat: Enhance user experience by including a comment section for star ratings

### ISSUE THREAD

**Issue by VictorCodebase** [Azure-Samples/contoso-real-estate#297]
**Are you accessing the project from the GitHub Codespaces?**

- [✅] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**✅Feature description**
Introducing a comment section alongside the star ratings will add depth and context to user reviews, making them more informative and valuable.
This feature will bring life to the star Ratin. Often users are curious; why a three-star rating? How bad is it really?

**✅Feature benefits**
⭕ Budget-Conscious Users: This feature empowers users with financial considerations to better evaluate trade-offs and get less regrets.

⭕ Personalized Assessments: What might be a concern for one user could be insignificant to another. By showcasing specific issues highlighted by reviewers, users can identify potential deal-breakers and make choices aligned with their preferences.

⭕ Enhanced Rating Credibility: The inclusion of comments elevates the trustworthiness of the existing star rating system, creating a more transparent and honest representation of user experiences.

⭕ By allowing comments too to be upvoted by other customers, malicious comments will very easily show ensuring users are protected.

**Screenshots**
Here are screenshots demonstrating what the review system will look like😃

![Screenshot 2023-08-21 020350](https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/695a5b2a-f3d8-4103-81e6-1856ef6c2420)

![Screenshot 2023-08-21 020407](https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/a495adae-5868-43eb-967e-02a54b5d4774)

**Additional input**

While this challenge represents a significant leap in my experience, I'm excited about the opportunity to implement customer reviews and comments.  
This will encompass new territories for me, such as routing and backend operations for efficiently storing reviews.

**Collaboration request**
As I embark on this ambitious project, I'd be honored if @anfibiacreativa could consider collaborating with me.
Your expertise would be invaluable in guiding me through this journey, and I believe it will be both a challenging and immensely enjoyable endeavor. Your insight would make a world of difference, and I'm eager to learn from you.

Thank you for considering this collaboration request, and I look forward to the potential for growth and accomplishment in this endeavor😃.

**Comment by anfibiacreativa** [comment]
Hi @VictorCodebase . Another great suggestion! Looking forward to your contribution and PR!

**Comment by kelvink96** [comment]
I can take up this task

**Comment by VictorCodebase** [comment]
Also; some of my suggestions were flagged as out of scope. Does that mean I could  proceed to work on them after the hackathon? 
I've just realized that I've learnt sooo much on creating reliable, scalable and efficient designs these few days Ive been working on this project. I think by continuing to collaborate with other developers I'll continue to adapt more skills on creating scalable and efficient designs.

**Comment by anfibiacreativa** [comment]
Closed. Out of scope.
