### ISSUE TITLE
[Kudos] Thanks for the Livestream! 

### ISSUE THREAD

**Issue by DanielHe4rt** [Azure-Samples/contoso-real-estate#301]
One of the coolest thing about being Brazilian is to see other Brazilians doing a cool job overseas. 

I never heard about the project and got really good insights! Me and the other members from @he4rt did an watch party and we loved the content presented!

![Watch Party at He4rt Developers Discord](https://github.com/Azure-Samples/contoso-real-estate/assets/6912596/dc914c55-d215-4f63-99b9-8f9c7cc32b69)

Huge kudos to @cyz and to @glaucia86 for this amazing content! We hope to have an event with both in São Paulo (maybe Reactor) soon! Let our community know if there's anything that we can contribute in the upcoming streams!

VAI BRASIL 🇧🇷 🤝

**Comment by Lucasnribeiro** [comment]
Yoooo let's gooooo!!! Brasil!!

**Comment by cristopherpds** [comment]
VAI BRASIL 🇧🇷 🤝

**Comment by IvanDragonV2** [comment]
Fala, galera! Let's go, Brazil!
![484bfdfe018ec31fc41cc14b1dbdd945](https://github.com/Azure-Samples/contoso-real-estate/assets/76605149/26965086-fb67-492a-82f0-ee147123a11f)

**Comment by israelcena** [comment]
🇧🇷 in all the world !

**Comment by RenanVidal** [comment]
go BR

**Comment by artenlf** [comment]
Let's go @he4rt
VAI BRASIL 🇧🇷 🤝

**Comment by willy-r** [comment]
In Brazil and He4rt we trust! 🇧🇷 🤝

**Comment by RodrigoRVSN** [comment]
Daleee

**Comment by cherryramatisdev** [comment]
Vai Brazil 🇧🇷🤝

**Comment by anfibiacreativa** [comment]
As a Uruguayan, all I can say is I <3 Brazil! Thank you for the amazing support from this community! We love having you all onboard!

**Comment by LucasMedeiros7** [comment]
BRASIL SIL SIL 🇧🇷🇧🇷🇧🇷
