### ISSUE TITLE
[Hack-together] docs: update global readme.md with `azd auth login` information

### ISSUE THREAD

**Issue by GmausDev** [Azure-Samples/contoso-real-estate#307]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [ ✔] Yes, I am using GitHub Codespaces.

**Describe the bug**

Currently the documentation in the part "Deploy to Azure" offers some steps that could be updated as it depends on how you connect from Codespaces can cause problems or even not connect.

![imagen](https://github.com/Azure-Samples/contoso-real-estate/assets/50465630/cd44a5e8-b8ee-4890-b20a-3ae5b05e60dd)

**To Reproduce**

1. Go to your Codespaces
2. Type in command azd auth login
3. Log in the azure account

**Expected behavior**
A screen that returns you to authorized Codespaces.

**Screenshots**
![imagen](https://github.com/Azure-Samples/contoso-real-estate/assets/50465630/fe93a902-b465-48d0-a1cf-668eb19383c9)
![imagen](https://github.com/Azure-Samples/contoso-real-estate/assets/50465630/de36cea0-9172-4c03-bc31-1eaf87b62cd8)

![imagen](https://github.com/Azure-Samples/contoso-real-estate/assets/50465630/35d8a8f5-d4d9-4d08-a12e-a6f5a8bbe709)

**OS (please complete the following information):**

- OS:Codespaces
- OS Version:Codespaces
- npm version: 
- Node.js version:
- output of `azd version`:  azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Additional context**
We could update the wiki to specify that using flags in the command can be solved

**Comment by ShatilKhan** [comment]
Hi @juliamuiruri4 ,
I created a pull request for this issue.
Please check to see if it is alright.
I would love to contribute more to any documentation or front-end related issues.

**Comment by ShatilKhan** [comment]
@juliamuiruri4 requesting for this issue assigning. See my PR for updates.
