### ISSUE TITLE
[Docs] Typos in README files

### ISSUE THREAD

**Issue by richardrigutins** [Azure-Samples/contoso-real-estate#311]
Hi, I noticed some minor typos across the various README.md files.

Here are some examples and the proposed corrections:

###  README.md
- `Read the [website/README](./packages/docs/website/README.md) more details on setting up and building this package.` (line 166, should be `... for more details ...`).

### packages/api/README.md
- `2. assumming you are in the folder containing your clone` (line 21, should be `assuming`).
- `Then, you need to add in your packages/api/.env file in the following content:` (line 36, looks like there's an extra `in`).

### packages/docs/README.md
- `content for _interactive workshops_ to explore sample in a hands-on, step-by-step manner ex` (line 12, should be `... to explore the sample ...`).
- `This command will start the dev server _and_ launch browser to the correct preview URL` (line 17, should be `... launch the browser ...`).

### packages/portal/README.md
- `independenty` (line 7, should be `independently`).
- `assumming` (line 26, should be `assuming`).
- `respository` (line 32, should be `repository`).

**Comment by ShatilKhan** [comment]
Hi @richardrigutins ,

I have raised a PR on this issue.
PR: #312 

Please have a look.

**Comment by ShatilKhan** [comment]
@juliamuiruri4 , Would be great if you assign me this, already opened a PR.

**Comment by anfibiacreativa** [comment]
Fixed with #312
