### ISSUE TITLE
[Bug] `azd auth login` in CodeSpaces fails to open browser 

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#318]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [X ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Expect `azd auth login` process to successfully open browser. I don't know if this is an issue with running CodeSpaces in browser or azd or this specific project. 

**To Reproduce**

1. In CodeSpace in browser, try `azd auth login`
2. Copy device code
4. Press enter as instructed
5. "Error launching browser. Manually go to: https://microsoft.com/devicelogin"
6. See error

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/a35cc22f-37f5-494a-8245-854490ba925c)

**Expected behavior**
Steps to complete login are successful in CodeSpaces.

**Screenshots**

**OS (please complete the following information):**

- OS: windows 11/edge
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by anfibiacreativa** [comment]
That is a known issue that has to do with the Azure (ADD) auth flow, and we can't fix.
Please refer to the docs here: https://github.com/Azure-Samples/contoso-real-estate#deploy-to-azure-1

There is a PR open to add this to our readme
