### ISSUE TITLE
[Hack-together] 

### ISSUE THREAD

**Issue by VickyTaar** [Azure-Samples/contoso-real-estate#324]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [ ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**

**To Reproduce**

2. Type in command '...'
3. Click on '...'
4. Scroll down to '...'
5. See error

**Expected behavior**

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by anfibiacreativa** [comment]
Hi @VickyTaar @juliamuiruri4  I cannot see the actual issue description here so I'm closing. Please let me know if I'm missing something.
