### ISSUE TITLE
[Chore] fuzz-run doesn't install

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#342]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [X ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
`npm i -g npm@latest fuzz-run` fails with incorrect version of node.

**To Reproduce**

`npm i -g npm@latest fuzz-run` returns

    ```
    npm ERR! code EBADENGINE
    npm ERR! engine Unsupported engine
    npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
    npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
    npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
    npm ERR! notsup Actual:   {"npm":"9.5.0","node":"v18.15.0"}
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/node/.npm/_logs/2023-09-19T19_00_25_392Z-debug-0.log
    ```

**Expected behavior**

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by anfibiacreativa** [comment]
This refers to the node engine/npm version not being compatible. Please check your versions.
