### ISSUE TITLE
[Chore] API can't use Azure PG locally due to .env issue

### ISSUE THREAD

**Issue by dfberry** [Azure-Samples/contoso-real-estate#343]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
The API package incorrectly uses the local .env file. 

**To Reproduce**

1. Provision resources: `azd provision`
2. Create local env file from /packages/api: `npm run env` which creates a .env file
3. From root, start API: `npm run start:api`
4. Try to get listings: `https://CodespacesURL/api/listings`
5. Get error about getting refused from postgres (local db)

**Expected behavior**
Local development successfully connects to Azure Postgres

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version: 
- Node.js version:
- output of `azd version`: 

**Additional context**

**Comment by anfibiacreativa** [comment]
Closed due to inactivity.
