### ISSUE TITLE
[Chore]  Debug with local or Azure services

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#347]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Currently, the project appears to be geared towards local development with local resources. See [issue 343](https://github.com/Azure-Samples/contoso-real-estate/issues/343). 

However, when trying to debug the API locally with launch file, the process used `azd restore`. It seems there isn't a consistent usage between local and cloud resources. Adding a debug launch configuration for local resources with a naming convention that noted is important to remain consistent with the local resources paradigm.

**Expected behavior**
Can debug against local or cloud resources.

**Comment by anfibiacreativa** [comment]
@diberry any updates to this issue?

**Comment by diberry** [comment]
This is Codespaces so I'll take another look next week when I have time.

**Comment by anfibiacreativa** [comment]
Closed due to inactivity.
