### ISSUE TITLE
Error deploying Postgres to eastus2

### ISSUE THREAD

**Issue by crazy4pi314** [Azure-Samples/contoso-real-estate#348]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
The sample fails to provision in the eastus2 region for folks with Microsoft internal Azure accounts, and gives a cryptic error message. This is documented in a few different repos, but here is the main reporting thread: https://github.com/Azure/azure-dev/issues/933

**To Reproduce**

1. Open codespaces and login to AZD and then run `azd provision`

```
/workspaces/contoso-real-estate (main) $ azd provision

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  You can view detailed progress in the Azure Portal:
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  (✓) Done: Resource group: rg-contoso-test
  (✓) Done: Static Web App: stapp-web-igsdtffkajqno
  (✓) Done: App Service plan: plan-igsdtffkajqno
  (✓) Done: Log Analytics workspace: log-igsdtffkajqno
  (✓) Done: Key Vault: kv-igsdtffkajqno
  (✓) Done: Storage account: stigsdtffkajqno
  (✓) Done: Application Insights: appi-igsdtffkajqno
  (✓) Done: Portal dashboard: dash-igsdtffkajqno
  (x) Failed: Azure Database for PostgreSQL flexible server: psql-db-igsdtffkajqno
  (✓) Done: Container Apps Environment: cae-igsdtffkajqno
  (✓) Done: Container Registry: crigsdtffkajqno
  (✓) Done: Azure Cosmos DB: cosmos-igsdtffkajqno

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ParameterOutOfRange: The value of the 'Version' should be in: []. Verify that the specified parameter value is correct.

```

**Expected behavior**
It should provision for everyone in that region, or at the least have an error message related to the real cause which is Microsoft company accounts cannot deploy postgres to that region.

**OS (please complete the following information):**
(devcontainer on hash fdd4be2455dec2c1fd54f3a36a81884711a6f97b)
- OS: Linux
- OS Version: mcr.microsoft.com/devcontainers/javascript-node:0-18
- npm version: 9.5.0
- Node.js version: 18.15.0
- output of `azd version`: azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)

**Comment by anfibiacreativa** [comment]
Hi @crazy4pi314 . Thanks for opening this issue. Seems like an improvement for AZD's feedback loop?

**Comment by anfibiacreativa** [comment]
Closing. Out of scope.
