### ISSUE TITLE
[Chore] (Portal) - GitHub login fails - redirect is empty

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#360]
1. On portal, select GitHub auth (with dev tools open)
2. View URL as `https://victorious-river-03cbdf403.3.azurestaticapps.net/.auth/login/github?post_login_redirect_uri=undefined`
3. Is this an issue with SWA build or AZD deploy? 
4. If I go back to root, I am logged in so not blocking but generally annoying.
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/e08f8277-f44b-4031-a4f5-ffb468752c42)

Har attached (remove .txt extension to use)
[20230925-github-social-login-victorious-river-03cbdf403.3.azurestaticapps.net.har.txt](https://github.com/Azure-Samples/contoso-real-estate/files/12718098/20230925-github-social-login-victorious-river-03cbdf403.3.azurestaticapps.net.har.txt)

**Comment by manekinekko** [comment]
I suspect this issue was introduced by this [commit](https://github.com/Azure-Samples/contoso-real-estate/commit/8c5c02f894570701f1c2bad82ea526fe4a6fdb85). It needs more investigations.
