### ISSUE TITLE
[Chore] Stripe/infra - steps to get stripe endpoint fail

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#363]
This step documented [here](https://github.com/Azure-Samples/contoso-real-estate/blob/main/docs/README-scenario-5.md#configuring-stripe). 

```
source .env && echo "Your Stripe webhook endpoint URL is:\n$SERVICE_STRIPE_URI/stripe-api/stripe/webhook"
```

fails with the following: 

```
source .env && echo "Your Stripe webhook endpoint URL is:\n$SERVICE_STRIPE_URI/stripe-api/stripe/webhook"
bash: Manage: command not found
bash: .env: line 4: syntax error near unexpected token `('
bash: .env: line 4: `  • An Application can have multiple environments (ex: dev, test, prod).'
```

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/ec6d058b-5174-42b5-ab56-e2495d78f008)

Obviously I can get the value from the .env file but the step needs to be fixed. 

Ran it in Codespaces.

**Comment by diberry** [comment]
Why are we creating a new .env file? It seems like it is yet another .env file that may be sitting around forever confusing developers.

**Comment by diberry** [comment]
Change `azd env get-env > .env` to `azd env get-values > .env`

**Comment by manekinekko** [comment]
Fixed by https://github.com/Azure-Samples/contoso-real-estate/pull/368
