### ISSUE TITLE
[Chore] (Portal) Apple auth fails

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#379]
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/f24a3cbb-9627-4d3a-a77a-bee97571f898)

**Comment by diberry** [comment]
@aaronpowell Since you own the [only doc in SWA that mentions apple auth](https://learn.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=apple%2Cinvitations), is apple auth _only available_ if a custom auth id and secret are provided for SWA?

**Comment by aaronpowell** [comment]
Yes, you need to be using a standard plan and provide the apple secret + id

**Comment by diberry** [comment]
@manekinekko @anfibiacreativa Can we remove apple for now?

**Comment by manekinekko** [comment]
Yes.

**Comment by anfibiacreativa** [comment]
@diberry any updates?

**Comment by dfberry** [comment]
@anfibiacreativa @manekinekko please close since this merged.
