### ISSUE TITLE
[Chore] azd asks for stripe secrets and keys

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#389]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [X ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
The repo `azd deploy` now asks for stripe secrets and keys. 

**To Reproduce**

1. `azd provision`
2. `azd deploy`
3. process asks for several stripe bits of information where it didn't before

**Expected behavior**
Not to ask for stripe since that is a more complex path. 

@sinedied "To prevent that, we need to update this file with default values, for example for the stripe key we should change it to "value": "${STRIPE_PUBLIC_KEY=''}" to set empty string as default."

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version:
- Node.js version:
- output of `azd version`:

**Additional context**

**Comment by diberry** [comment]
Getting `Container App Environment is not ready for container app creation as it is in state 'Waiting'. Hoping that is temporary.

**Comment by dfberry** [comment]
merged so please close @anfibiacreativa @manekinekko

**Comment by manekinekko** [comment]
Fixed by https://github.com/Azure-Samples/contoso-real-estate/pull/391
