### ISSUE TITLE
[Chore] Portal package has 2 apollo-angular dependencies listed. 

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#393]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [X ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
I think the two versions of the same package is incorrect. @anfibiacreativa @manekinekko 

**To Reproduce**

Main branch file showing both versions. 
* line 28: "apollo-angular": "^4.2.1",
* line 33: "apollo-angular": "^5.0.1",

I assume this was a bad merge? 

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/8fc738b6-473c-4fc2-96c4-d46c1acffc82)

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version:
- Node.js version:
- output of `azd version`:

**Additional context**

**Comment by diberry** [comment]
Related to #392?

**Comment by manekinekko** [comment]
> I assume this was a bad merge?
Yes. The right version is 5+. I am going to send a PR.

**Comment by diberry** [comment]
#396 - related
