### ISSUE TITLE
[Chore] api-v4 package: double entry of `@azure/functions`

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#396]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [ ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Not sure when this happened - I assume its just a bad merge. @glaucia86 can you take a look? 

```
 "@azure/functions": "^4.0.0",
 "@azure/functions": "^1.2.3",
```

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/d70536f2-7ed6-49a5-ab78-f53737549179)
**Expected behavior**

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version:
- Node.js version:
- output of `azd version`:

**Additional context**

**Comment by glaucia86** [comment]
> **Are you accessing the project from the GitHub Codespaces?**
> 
> * [ ]  No, I am running the project on my local machine (I will fill in the OS section below)
> * [ ]  Yes, I am using GitHub Codespaces.
> 
> > Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!
> 
> **Describe the bug** Not sure when this happened - I assume its just a bad merge. @glaucia86 can you take a look?
> 
> ```
>  "@azure/functions": "^4.0.0",
>  "@azure/functions": "^1.2.3",
> ```
> 
> ![image](https://user-images.githubusercontent.com/41597107/280137958-d70536f2-7ed6-49a5-ab78-f53737549179.png) **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **OS (please complete the following information):**
> 
> * OS:
> * OS Version:
> * npm version:
> * Node.js version:
> * output of `azd version`:
> 
> **Additional context** Add any other context about the problem here.

Yes. I will try to invastigate this
