### ISSUE TITLE
[Chore] Azure Functions API: switch `console.` to `context.`

### ISSUE THREAD

**Issue by dfberry** [Azure-Samples/contoso-real-estate#405]
In Azure Functions, console.x output is only available when streaming log or at the Function app level. The context.x output is available at the API level within the Function app. 

There are several console.x calls in the startup code which would only be helpful in active debugging. Switch to using context.x which means it needs to be passed down from the api to the startup functionality. It could also, potentially, be rolled into the logger module which handles output to applicationInsights.

**Comment by glaucia86** [comment]
@dfberry do you mean the `api-v4` the new api?

**Comment by dfberry** [comment]
@glaucia86 Its true for either version but no need to update the v3. Once the updates for v4 is merged, the api-v4 becomes api. So only func v4 pm needs to be updated.

**Comment by glaucia86** [comment]
I can take this one, once the v4 is merged

**Comment by anfibiacreativa** [comment]
Closed due to inactivity.
