### ISSUE TITLE
[Chore] Move active development to a DEV branch

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#407]
Move active development to DEV branch. Leave main for periodic updates after extensive CI testing and deployment testing.

**Comment by anfibiacreativa** [comment]
Hi @diberry . That would require a release schedule or strategy. I can open a develop branch, and change the base branch for all current active PRs, but for the future, we may need to think this through a bit more in depth.

**Comment by anfibiacreativa** [comment]
created dev branch and updated base branch for existing PRs
