### ISSUE TITLE
[Chore] Fix Fns app to work by default

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#414]
The local.settings.json.sample file needs to be renamed to just `local.settings.json`. Its already in the .ignore file so this should be ok. The current system means the api doesn't start successfully and new users don't know why. 

@glaucia86 Thoughts?

**Comment by glaucia86** [comment]
Hi, @diberry! I can take this one too. And yes. Looks like with the new update from the new version we can use the `local.settings.json`. My intention to create a sample file is for mention to the audience the importance to create this file once they want to test locally the `api`.

Once I'm back from my OOF, I will try to back to you to understand better about that :)

**Comment by glaucia86** [comment]
Hi, @diberry! To avoid conflict with your API PR https://github.com/Azure-Samples/contoso-real-estate/pull/40, I will proceed with this issue (just to let you know)

**Comment by manekinekko** [comment]
Fixed in #438
