### ISSUE TITLE
[Chore] Add Azure resources vscode extension

### ISSUE THREAD

**Issue by dfberry** [Azure-Samples/contoso-real-estate#425]
At some point in the last few months, the Azure resources extension was changed from default install for any Azure extensions to a developer having to add it manually. I don't know if this is a bug or expected behavior but it will trip up a new Azure user for this repo. 

Add Azure resources extension to .devcontainer extensions list.

**Comment by diberry** [comment]
This looks fixed to me now - on the extension side - not on the contoso side.
