### ISSUE TITLE
[Chore][Api][Portal] Create isomorphic library with models and business logic

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/contoso-real-estate#73]
Models and they typings are shared between API and Portal, so we should extract them into a seperate package (as we're using a workspaces monorepo) and include also shared business logic, like price calculation.

- [ ] Create package `common`
- [ ] Extract models types into this package and use them in API/Portal
- [ ] Extract common business logic and use it in API/Portal

**Comment by manekinekko** [comment]
Won't implement due to lack of time.
